image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

# Setup a cache to cache job parts between jobs to ensure faster builds
cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - $HOME/.cargo/
    - target/

# Set any required environment variables here
variables:
  RUST_BACKTRACE: "FULL"

stages:
  - build
  - test

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

test-code:
  stage: test
  script:
    - cargo test
    - cargo install cargo-tarpaulin -f
    - cargo tarpaulin --ignore-tests
  coverage: '/^\d+.\d+% coverage/'

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

format-code:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit-code:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit
