image: "rust:latest"

default:
  before_script:
    - hostname -I
    - whoami

# Setup a cache to cache job parts between jobs to ensure faster builds
cache:
  - key: "$CI_JOB_NAME"
    untracked: true
    paths:
      - $CI_PROJECT_DIR/target/

# Set any required environment variables here
variables:
  RUST_BACKTRACE: "FULL"

stages:
  - code-quality
  - build-and-test
  - build-release

pre-commit:
  image: python:3.9
  stage: code-quality
  script:
    - python3 --version
    - pre-commit --version
    - pre-commit run --all-files --show-diff-on-failure

lint:
  stage: code-quality
  script:
    - rustc --version
    - cargo --version
    - rustup component add clippy
    - cargo clippy -- -D warnings

format:
  stage: code-quality
  script:
    - rustc --version
    - cargo --version
    - rustup component add rustfmt
    - cargo fmt -- --check

audit:
  stage: code-quality
  script:
    - rustc --version
    - cargo --version
    - cargo install cargo-audit
    - cargo audit

rust-latest:
  stage: build-and-test
  image: rust:latest
  script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
    - cargo test --verbose
  artifacts:
    name: "_d_${CI_COMMIT_SHA}"
    paths:
    - ./target
    expire_in: 3 mos

rust-nightly:
  stage: build-and-test
  image: rustlang/rust:nightly
  script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

## For release build
build-release-latest:
  stage: build-release
  only:
    - release
  image: rust:latest
  script:
    - rustc --version
    - cargo --version
    - cargo build -r --verbose
  artifacts:
    name: "$_r_{CI_COMMIT_SHA}"
    paths:
    - ./target
    expire_in: 5 mos
