# The Docker image that will be used to build your app
image: rust:latest
# Functions that should be executed before the build script is run
before_script:
  - hostname -I
  - whoami
  - rustc --version
  - cargo --version
pages:
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
