[package]
name = "fastpasta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[dependencies]
atty = "0.2.14"
byteorder = "1.4.3"
clippy = "0.0.302"
criterion = "0.4.0"
crossbeam-channel = "0.5.6"
fmt = "0.1.0"
log = "0.4.17"
sm = "0.9.0"
stderrlog = "0.5.4"
structopt = "0.3.26"

[[bench]]
name = "io_benchmark"
harness = false
