[package]
name = "fastpasta"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[dependencies]
atty = "0.2.14"
byteorder = "1.4.3"
criterion = "0.4.0"
crossbeam-channel = "0.5.6"
fmt = "0.1.0"
gag = "1.0.0"
itertools = "0.10.5"
log = "0.4.17"
owo-colors = "3.5.0"
sm = "0.9.0"
stderrlog = "0.5.4"
structopt = "0.3.26"
tabled = { version = "0.10.0", features = ["color"]}

[[bench]]
name = "io_benchmark"
harness = false
