[package]
name = "fastpasta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[dependencies]
byteorder = "1.4.3"
criterion = "0.4.0"
crossbeam-channel = "0.5.6"
fmt = "0.1.0"
sm = "0.9.0"
structopt = "0.3.26"

[[bench]]
name = "io_benchmark"
harness = false
