[package]
name = "fastpasta_toml_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastpasta_toml_macro_derive = { version = "0.1.0", path = "fastpasta_toml_macro_derive" }
