@startuml sequence_view_mode
skinparam RoundCorner 7
skinparam sequenceDivider {
    BorderThickness 1
}
skinparam participant {
    BackgroundColor FF6F61
    'BorderColor 454645
    FontColor White
    BorderThickness 1.5
}
skinparam queue {
    BackgroundColor FF6F61
    BorderColor 454645
    FontColor FFF
    BorderThickness 1.5
}
skinparam style strictuml
' Carto color palette
' light blue       #88CCEE
' light pink/red   #CC6677
' light yellow     #DDCC77
' dark green       #117733
' Dark purple      #332288
' Pink             #AA4499
' Light blue/green #44AA99
' Brown/yellow     #999933
' Dark purple      #882255
' Dark red         #661100
' Medium blue      #6699CC
' Grey             #888888

Title **<size:30>fastPASTA sequence diagram</size>**\n<< View mode >>

participant InputScanner as inputscanner << input >>
queue InputData as inputfifo << FIFO >> #6699CC
participant ViewGenerator as viewgenerator << view >>
queue StatsData as statsfifo << FIFO >> #44AA99
participant StatsController as statscontroller << stats >>


par

    loop !end-of-file

        inputscanner -> inputscanner : load data
    activate inputscanner #gold
        inputscanner --> statsfifo : send stats
        inputscanner --> inputfifo : send data
    deactivate inputscanner
    end
destroy inputscanner

else
    loop !<color #6699CC>**InputData**</color> empty && <color #6699CC>**InputData**</color> connected

        viewgenerator -> inputfifo : get data
    activate viewgenerator #gold
        inputfifo --> viewgenerator : data

        viewgenerator -> viewgenerator : Format &\nprint data view

    deactivate viewgenerator
    end
    destroy inputfifo
destroy viewgenerator
else
    loop !<color #44AA99>**StatsData**</color> empty &&\n<color #44AA99>**StatsData**</color> connected
        statscontroller -> statsfifo : get stat
    activate statscontroller #gold
        statsfifo --> statscontroller : stat
        statscontroller -> statscontroller : record stat
        opt stat == error
            statscontroller -> statscontroller : print error\nmessage
        end
    end
    statscontroller -> statscontroller : print summary
    deactivate statscontroller
destroy statsfifo
destroy statscontroller

end




@enduml
