cargo-features = ["profile-rustflags"]
[unstable]
profile-rustflags = true

# Experimental build that is more performant
# Can only be build with the nightly toolchain
# e.g. $ cargo +nightly build --profile release-nightly
[profile.release-nightly]
inherits = "release"
lto = true
codegen-units = 1
rustflags = ["-C", "llvm-args=-inline-threshold=335"]

# Disabled because it causes problems on GitLab CI atm (2024-05-22)
# tracking issue: https://gitlab.cern.ch/mkonig/fastpasta/-/issues/47
# [build]
# rustflags = ["-C", "target-cpu=native"]
